# Generated by Django 5.0.2 on 2024-02-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndvi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndvi',
            name='ndvi',
            field=models.FloatField(default=0.0),
        ),
    ]
