# Generated by Django 5.0.2 on 2024-02-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndvi', '0002_ndvi_ndvi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ndvi',
            name='time',
        ),
        migrations.AddField(
            model_name='ndvi',
            name='end_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ndvi',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
