# Generated by Django 5.0.2 on 2024-02-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndvi', '0003_remove_ndvi_time_ndvi_end_date_ndvi_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndvi',
            name='end_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ndvi',
            name='start_date',
            field=models.TextField(),
        ),
    ]
