# Generated by Django 5.0.2 on 2024-02-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndvi', '0004_alter_ndvi_end_date_alter_ndvi_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndvi',
            name='cvs_data',
            field=models.TextField(default=''),
        ),
    ]
